//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Section106.Repository.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clock
    {
        public long ClockId { get; set; }
        public long RequestId { get; set; }
        public Nullable<System.DateTime> ClockDate { get; set; }
        public short ClockStatus { get; set; }
        public string Reason { get; set; }
        public Nullable<int> RemainingDays { get; set; }
        public Nullable<System.DateTime> InternalClockDate { get; set; }
        public Nullable<short> InternalClockStatus { get; set; }
        public Nullable<int> InternalRemainingDays { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
