//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Section106.Repository.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestResponse
    {
        public long RequestResponseId { get; set; }
        public long RequestId { get; set; }
        public long RequestAssignmentId { get; set; }
        public Nullable<bool> IsNoHistoricProperty { get; set; }
        public Nullable<bool> IsHistoricProperty { get; set; }
        public Nullable<short> ArchitectResponse { get; set; }
        public string ArchitectComment { get; set; }
        public string ArchitectUserId { get; set; }
        public Nullable<bool> IsSurveyRequired { get; set; }
        public Nullable<bool> IsMoreInfoRequired { get; set; }
        public Nullable<bool> IsArchaeologyNoHistoricProperty { get; set; }
        public Nullable<bool> IsArchaeologyHistoricProperty { get; set; }
        public Nullable<bool> IsArchaeologyNoEffect { get; set; }
        public Nullable<bool> IsArchaeologyNoAdverseEffect { get; set; }
        public Nullable<bool> IsArchaeologyAdverseEffect { get; set; }
        public Nullable<short> ArchaelogicalResponse { get; set; }
        public string ArchaelogicalComment { get; set; }
        public string ArchaelogicalUserId { get; set; }
        public Nullable<bool> IsTechnicalNoEffect { get; set; }
        public Nullable<bool> IsTechnicalNoAdverseEffect { get; set; }
        public Nullable<bool> IsTechnicalAdverseEffect { get; set; }
        public Nullable<short> TechnicalResponse { get; set; }
        public string TechnicalComment { get; set; }
        public string TechnicalUserId { get; set; }
        public Nullable<int> ArchaelogicalEligibleProperties { get; set; }
        public Nullable<int> ArchaelogicalInEligibleProperties { get; set; }
        public Nullable<int> ArchaelogicalUnknownProperties { get; set; }
        public Nullable<int> ArchitectEligibleProperties { get; set; }
        public Nullable<int> ArchitectInEligibleProperties { get; set; }
        public Nullable<int> ArchitectUnknownProperties { get; set; }
        public Nullable<short> LankMarksResponse { get; set; }
        public string LankMarksComment { get; set; }
        public string LankMarksUserId { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual RequestAssignment RequestAssignment { get; set; }
    }
}
