//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Section106.Repository.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Attachments = new HashSet<Attachment>();
            this.Clocks = new HashSet<Clock>();
            this.Correspondences = new HashSet<Correspondence>();
            this.RequestAssignments = new HashSet<RequestAssignment>();
            this.RequestResponses = new HashSet<RequestResponse>();
        }
    
        public long RequestId { get; set; }
        public string UserId { get; set; }
        public long ApplicantContactId { get; set; }
        public Nullable<bool> IsApplicantSameAsSubmitting { get; set; }
        public int Status { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string LogNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> CountyId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Zip { get; set; }
        public Nullable<decimal> LongitudeDD { get; set; }
        public Nullable<decimal> LatitudeDD { get; set; }
        public string Township { get; set; }
        public string Range { get; set; }
        public string Section { get; set; }
        public Nullable<bool> IsFederalProperty { get; set; }
        public Nullable<bool> IsStateProperty { get; set; }
        public Nullable<bool> IsMunicipalProperty { get; set; }
        public Nullable<bool> IsPrivateProperty { get; set; }
        public long AgencyId { get; set; }
        public string AgencyProjectNumber { get; set; }
        public Nullable<bool> IsConstructionExcavation { get; set; }
        public Nullable<bool> IsRehabilitation { get; set; }
        public Nullable<bool> IsDemolition { get; set; }
        public Nullable<bool> IsSaleOrTransfer { get; set; }
        public Nullable<bool> IsNonConstructionLoan { get; set; }
        public Nullable<bool> IsOther { get; set; }
        public string OtherDescription { get; set; }
        public Nullable<int> TotalProjectArea { get; set; }
        public Nullable<int> TotalGroundDisturbance { get; set; }
        public Nullable<bool> IsOldStructure { get; set; }
        public Nullable<short> IsHistoricOrGovtProperty { get; set; }
        public string HistoricPropertyName { get; set; }
        public Nullable<bool> IsDocumentSentViaEmail { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsMississippiLandmarks { get; set; }
        public Nullable<bool> IsProjectCompleted { get; set; }
        public Nullable<System.DateTime> ProjectCompleteddate { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clock> Clocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Correspondence> Correspondences { get; set; }
        public virtual County County { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestAssignment> RequestAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestResponse> RequestResponses { get; set; }
    }
}
