//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Section106.Repository.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestAssignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestAssignment()
        {
            this.RequestResponses = new HashSet<RequestResponse>();
        }
    
        public long RequestAssignmentId { get; set; }
        public long RequestId { get; set; }
        public Nullable<short> FederalOrState { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<System.DateTime> RespondDate { get; set; }
        public bool IsAssignToArchitect { get; set; }
        public bool IsAssignToArchaelogical { get; set; }
        public bool IsAssignToTechnical { get; set; }
        public Nullable<int> ArchitechStatus { get; set; }
        public Nullable<int> ArchaelogicalStatus { get; set; }
        public Nullable<int> TechnicalStatus { get; set; }
        public bool IsAssignToLandMarks { get; set; }
        public int LandMarksStatus { get; set; }
    
        public virtual Request Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestResponse> RequestResponses { get; set; }
    }
}
