//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Section106.Repository.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Section106Entities : DbContext
    {
        public Section106Entities()
            : base("name=Section106Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Agency> Agencies { get; set; }
        public virtual DbSet<AgencyType> AgencyTypes { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<Clock> Clocks { get; set; }
        public virtual DbSet<Correspondence> Correspondences { get; set; }
        public virtual DbSet<CorrespondenceType> CorrespondenceTypes { get; set; }
        public virtual DbSet<County> Counties { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Applicant> Applicants { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<RequestAssignment> RequestAssignments { get; set; }
        public virtual DbSet<RequestResponse> RequestResponses { get; set; }
    
        public virtual ObjectResult<GetSubmitterRequestsByStatus_Result> GetSubmitterRequestsByStatus(string statusList, string userId)
        {
            var statusListParameter = statusList != null ?
                new ObjectParameter("StatusList", statusList) :
                new ObjectParameter("StatusList", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSubmitterRequestsByStatus_Result>("GetSubmitterRequestsByStatus", statusListParameter, userIdParameter);
        }
    }
}
